server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:

- job_name: pod
  pipeline_stages:
    - match:
        selector: '{job="pod-logs"}'
        stages:
        - regex: 
            source: filename
            expression: '^.*/namespaces/(?P<kubernetes_namespace_name>.*)/pods/(?P<kubernetes_pod_name>.*)/(?P<kubernetes_container_name>.*)/.*/logs/.*.log'
            #expression: '^.*/sosreport-(?P<node>.*)-\d{4}.*/var/log/pods/(?P<namespace>.*)_(?P<pod>.*)_.*/(?P<container>.*)/.*.log'
        - labels:
            kubernetes_namespace_name:
            kubernetes_pod_name:
            kubernetes_container_name:
    - regex:
        expression: '^(?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{9}\+\d{2}:\d{2}) .*'
    - timestamp:
        format: RFC3339Nano
        source: time
  static_configs:
  - targets:
      - localhost
    labels:
      job: pod-logs
      __path__: /logs/registry-redhat*/namespaces/*/pods/*/*/*/logs/*.log
